import Head from "next/head";
import FormComponent from "../components/sapphire/Form-component";
import ImageCarouselComponent from "../components/sapphire/imagecarousel-component";
import ImagewithOverlayComponent from "../components/sapphire/imagewithoverlay-component";
import PartnerComponent from "../components/sapphire/partner-component";
import PortfolioComponent from "../components/sapphire/portfolio-component";
import PromoComponent from "../components/sapphire/promo-component";
import ServiceTabsComponent from "../components/sapphire/servicetabs-component";
import TestimonialComponent from "../components/sapphire/testimonial-component";
import { getAllCustompage } from "../lib/sapphire/custompage-lib";
import Custompage from "../types/Sapphire/custompage-type";
import Image from 'next/image';
import CustomFooterComponent from "../components/sapphire/footer-component";
import HeaderComponent from "../components/sapphire/header-component";
 
export async function getStaticProps({ preview = false}){
    const allCustompage = await getAllCustompage(preview);
    return{
        props: {allCustompage,  preview},
        // Next.js will attempt to re-generate the page:
        // - When a request comes in
        // - At most once every 10 seconds
        revalidate: 10, //in seconds
    }
    
  }
  
  type Props = {
    allCustompage: Custompage[];
  }
  
  const Custompage = ({allCustompage}: Props) => {
    const custompage = allCustompage[0];
  return (
    
<div className="container">   
    
     <Head>
    <title>Sapphire Homepage</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Raleway:400,700&display=swap" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" />

  <link href="../../styles/sapphire/Sapphirepage.module.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <script src="/js/custom.js" />


</Head>

<main className="container">
  
 <div className="hero area"><HeaderComponent allHeaders={custompage.header} /> <ImageCarouselComponent allImageCarousel={custompage.carousel} /> </div>

<div>
  <ServiceTabsComponent allServiceTabs={custompage.services} />
  </div>
 
 <div><PortfolioComponent allPortfolio={custompage.portfolio}/></div>
 <div> <PartnerComponent allPartner={custompage.partners} /> </div>
 <div> <PromoComponent allPromo={custompage.promo} /></div>
 <div><ImagewithOverlayComponent allImagewithOverlay={custompage.aboutsection} /></div>
   <FormComponent allForm={custompage.form} />
   <TestimonialComponent allTestimonial={custompage.feedback}/>
  <CustomFooterComponent />
</main>
</div>

  )
  }
  export default Custompage;
